<Project>
  <PropertyGroup>
    <Version Condition="'$(BUILD_VERSION)' == ''">5.0.0</Version>
    <Version Condition="'$(BUILD_VERSION)' != ''">$(BUILD_VERSION)</Version>
    <RepositoryUrl>https://github.com/soenneker/soenneker.flywheel.suite</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
