<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TailwindGeneratorBuildEnabled>true</TailwindGeneratorBuildEnabled>
    <IsPackable>false</IsPackable>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts/**;out/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Soenneker.Quark.Suite" Version="4.0.1361" />
    <PackageReference Include="Soenneker.Quark.Gen.Tailwind" Version="4.0.247" PrivateAssets="all" />
    <PackageReference Include="Soenneker.Quark.Gen.Lucide" Version="4.0.243" PrivateAssets="all" />
    <PackageReference Include="Soenneker.Lucide.Icons" Version="5.0.76" PrivateAssets="all" />
  </ItemGroup>
</Project>
