using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Soenneker.Flywheel.Generators;

[Generator]
public sealed class FlywheelGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor _signature = new("FW001", "Invalid job signature",
        "Job '{0}' must be a public instance method on a public non-generic non-nested class, accepting a payload and CancellationToken, returning Task or ValueTask",
        "Flywheel", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor _duplicate = new("FW002", "Invalid job identity",
        "Job name '{0}' must be unique, non-empty, and at most 200 characters; job methods cannot be overloaded",
        "Flywheel", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor _cron = new("FW003", "Invalid cron schedule declaration",
        "Cron schedule '{0}' requires a FlywheelJob method, a non-empty expression and time zone, and a unique schedule ID of at most 200 characters",
        "Flywheel", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor _policy = new("FW004", "Invalid job policy declaration",
        "Job '{0}' has invalid metadata; description must be at most 500 characters, concurrency and rate limit cannot be negative, and the rate window must be between 1 and 31,536,000 seconds",
        "Flywheel", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<IMethodSymbol>> methods = context.SyntaxProvider
                                                                                 .ForAttributeWithMetadataName("Soenneker.Flywheel.Core.Attributes.FlywheelJobAttribute",
                                                                                     static (_, _) => true, static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol).Collect();
        context.RegisterSourceOutput(methods, Emit);
        IncrementalValuesProvider<IMethodSymbol> cronMethods = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Soenneker.Flywheel.Core.Attributes.FlywheelCronAttribute", static (_, _) => true,
            static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol);
        context.RegisterSourceOutput(cronMethods, static (output, method) =>
        {
            if (!method.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == "Soenneker.Flywheel.Core.Attributes.FlywheelJobAttribute"))
                output.ReportDiagnostic(Diagnostic.Create(_cron, method.Locations.FirstOrDefault(), method.Name));
        });
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        IMethodSymbol[] valid = methods.Distinct(SymbolEqualityComparer.Default).OfType<IMethodSymbol>()
                                       .OrderBy(x => x.ToDisplayString()).ToArray();
        string[] names = valid.Select(Name).ToArray();
        var nameCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        var symbolCounts = new Dictionary<string, int>(StringComparer.Ordinal);
        var symbols = new string[valid.Length];
        for (var i = 0; i < valid.Length; i++)
        {
            nameCounts.TryGetValue(names[i], out int nameCount);
            nameCounts[names[i]] = nameCount + 1;
            string symbol = valid[i].ContainingType.Name + "_" + valid[i].Name;
            symbols[i] = symbol;
            symbolCounts.TryGetValue(symbol, out int symbolCount);
            symbolCounts[symbol] = symbolCount + 1;
        }
        const string header =
            "// <auto-generated/>\n#nullable enable\nnamespace Soenneker.Flywheel.Generated {\npublic static partial class FlywheelJobs {\n";
        var sb = new StringBuilder(header);
        var registrations = new StringBuilder();
        var schedulePreparation = new StringBuilder();
        var scheduleRegistrations = new StringBuilder();
        var scheduleIds = new HashSet<string>(StringComparer.Ordinal);
        for (var i = 0; i < valid.Length; i++)
        {
            IMethodSymbol m = valid[i];
            string name = names[i];
            if (string.IsNullOrWhiteSpace(name) || name.Length > 200 || nameCounts[name] != 1 ||
                m.ContainingType.GetMembers(m.Name).OfType<IMethodSymbol>().Count() != 1)
            {
                context.ReportDiagnostic(Diagnostic.Create(_duplicate, m.Locations.FirstOrDefault(), name));
                continue;
            }

            if (!IsValid(m))
            {
                context.ReportDiagnostic(Diagnostic.Create(_signature, m.Locations.FirstOrDefault(), m.Name));
                continue;
            }

            string type = m.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string payload = m.Parameters[0].Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string symbol = symbols[i];
            if (symbolCounts[symbol] > 1)
                symbol += "_" + string.Concat(Encoding.UTF8.GetBytes(m.ContainingType.ToDisplayString())
                                                      .Select(b => b.ToString("x2")));
            string literal = SymbolDisplay.FormatLiteral(name, true);
            AttributeData jobAttribute = m.GetAttributes().First(a =>
                a.AttributeClass?.ToDisplayString() == "Soenneker.Flywheel.Core.Attributes.FlywheelJobAttribute");
            int maxConcurrency = NamedInt(jobAttribute, "MaxConcurrency");
            int rateLimit = NamedInt(jobAttribute, "RateLimit");
            int rateWindowSeconds = NamedInt(jobAttribute, "RateWindowSeconds", 60);
            string? description = NamedString(jobAttribute, "Description");
            if (description?.Length > 500 || maxConcurrency < 0 || rateLimit < 0 || rateWindowSeconds is < 1 or > 31_536_000)
            {
                context.ReportDiagnostic(Diagnostic.Create(_policy, m.Locations.FirstOrDefault(), name));
                continue;
            }
            AppendJobDocumentation(sb, m, name);
            sb.Append("public static global::Soenneker.Flywheel.Communication.Dtos.JobDefinition<").Append(payload).Append("> @")
              .Append(symbol).Append(" { get; } = new(").Append(literal);
            if (description is not null)
                sb.Append(", ").Append(SymbolDisplay.FormatLiteral(description, true));
            sb.Append(");\n");
            AttributeData? cron = m.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "Soenneker.Flywheel.Core.Attributes.FlywheelCronAttribute");
            if (cron is not null)
            {
                string expression = cron.ConstructorArguments.FirstOrDefault().Value as string ?? "";
                string scheduleId = cron.NamedArguments.FirstOrDefault(a => a.Key == "Id").Value.Value as string ??
                                    name;
                string zone = cron.NamedArguments.FirstOrDefault(a => a.Key == "TimeZoneId").Value.Value as string ??
                              "UTC";
                string json = cron.NamedArguments.FirstOrDefault(a => a.Key == "PayloadJson").Value.Value as string ??
                              "{}";
                string seconds = cron.NamedArguments.FirstOrDefault(a => a.Key == "IncludeSeconds").Value.Value is true
                    ? "true"
                    : "false";
                if (string.IsNullOrWhiteSpace(expression) || expression.Length > 200 ||
                    string.IsNullOrWhiteSpace(zone) || zone.Length > 200 || string.IsNullOrWhiteSpace(scheduleId) ||
                    scheduleId.Length > 200 || !scheduleIds.Add(scheduleId))
                    context.ReportDiagnostic(Diagnostic.Create(_cron, m.Locations.FirstOrDefault(), scheduleId));
                else
                {
                    string expressionLiteral = SymbolDisplay.FormatLiteral(expression, true);
                    string zoneLiteral = SymbolDisplay.FormatLiteral(zone, true);
                    schedulePreparation.Append("_ = global::Soenneker.Cron.Parser.CronParser.Parse(")
                                       .Append(expressionLiteral).Append(", ").Append(zoneLiteral).Append(", ")
                                       .Append(seconds).Append(");\n").Append("var payload").Append(i)
                                       .Append(" = global::Soenneker.Utils.Json.JsonUtil.Deserialize<")
                                       .Append(payload).Append(">(").Append(SymbolDisplay.FormatLiteral(json, true))
                                       .Append(");\n");
                    scheduleRegistrations.Append("await client.Schedule(")
                                         .Append(SymbolDisplay.FormatLiteral(scheduleId, true)).Append(", @")
                                         .Append(symbol).Append(", payload").Append(i).Append("!, ")
                                         .Append(expressionLiteral).Append(", ").Append(zoneLiteral)
                                         .Append(", includeSeconds: ").Append(seconds)
                                         .Append(", cancellationToken: cancellationToken);\n");
                }
            }

            var invoker = new StringBuilder(header);
            invoker.Append("private sealed class Invoker").Append(i)
                   .Append(" : global::Soenneker.Flywheel.Core.Services.Abstract.IJobInvoker {\npublic string Name => ")
                   .Append(literal)
                   .Append(";\n");
            if (maxConcurrency != 0 || rateLimit != 0)
                invoker.Append("public global::Soenneker.Flywheel.Communication.Dtos.MethodPolicy Policy { get; } = new() { MaxConcurrency = ")
                       .Append(maxConcurrency == 0 ? "null" : maxConcurrency.ToString())
                       .Append(", RateLimit = ").Append(rateLimit == 0 ? "null" : rateLimit.ToString())
                       .Append(", RateWindow = global::System.TimeSpan.FromSeconds(").Append(rateWindowSeconds).Append(") };\n");
            invoker.Append(
                       "public async global::System.Threading.Tasks.Task Invoke(global::System.IServiceProvider services, string payload, global::System.Threading.CancellationToken ct) {\n")
                   .Append(
                       "var handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<")
                   .Append(type).Append(">(services);\n")
                   .Append("var value = global::Soenneker.Utils.Json.JsonUtil.Deserialize<").Append(payload)
                   .Append(">(payload);\n").Append("await handler.@").Append(m.Name)
                   .Append("(value!, ct);\n}}\n}\n}\n");
            context.AddSource("FlywheelJobs.Invoker" + i + ".g.cs", invoker.ToString());
            registrations
                .Append(
                    "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<")
                .Append(type).Append(">(builder.Services);\n").Append(
                    "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(builder.Services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<global::Soenneker.Flywheel.Core.Services.Abstract.IJobInvoker, Invoker")
                .Append(i).Append(">());\n");
        }

        if (scheduleRegistrations.Length != 0)
            sb.Append(
                  "/// <summary>Registers declared cron schedules. Existing schedule IDs are unchanged. Call after building the host.</summary>\n")
              .Append(
                  "public static async global::System.Threading.Tasks.Task RegisterGeneratedSchedules(this global::Soenneker.Flywheel.Core.Services.Abstract.IJobClient client, global::System.Threading.CancellationToken cancellationToken = default) {\n")
              .Append(schedulePreparation).Append(scheduleRegistrations).Append("}\n");
        sb.Append(
              "public static global::Soenneker.Flywheel.Core.Registrars.FlywheelBuilder AddGeneratedJobs(this global::Soenneker.Flywheel.Core.Registrars.FlywheelBuilder builder) {\n")
          .Append(registrations).Append("return builder;\n}\n}\n}\n");
        context.AddSource("FlywheelJobs.g.cs", sb.ToString());
    }

    private static string Name(IMethodSymbol method) => method.GetAttributes()
                                                              .First(x => x.AttributeClass?.ToDisplayString() ==
                                                                          "Soenneker.Flywheel.Core.Attributes.FlywheelJobAttribute")
                                                              .ConstructorArguments.FirstOrDefault().Value as string ??
                                                        "";

    private static int NamedInt(AttributeData attribute, string name, int defaultValue = 0)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
            if (argument.Key == name && argument.Value.Value is int value)
                return value;
        return defaultValue;
    }

    private static string? NamedString(AttributeData attribute, string name)
    {
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
            if (argument.Key == name)
                return argument.Value.Value as string;
        return null;
    }

    private static void AppendJobDocumentation(StringBuilder source, IMethodSymbol method, string name)
    {
        string? documentation = method.GetDocumentationCommentXml();
        if (string.IsNullOrWhiteSpace(documentation))
        {
            foreach (INamedTypeSymbol contract in method.ContainingType.AllInterfaces)
            {
                IMethodSymbol? member = contract.GetMembers().OfType<IMethodSymbol>().FirstOrDefault(candidate =>
                    SymbolEqualityComparer.Default.Equals(
                        method.ContainingType.FindImplementationForInterfaceMember(candidate), method));
                if (member is null)
                    continue;
                documentation = member.GetDocumentationCommentXml();
                if (!string.IsNullOrWhiteSpace(documentation))
                    break;
            }
        }

        XElement? summary = null;
        try
        {
            if (!string.IsNullOrWhiteSpace(documentation))
                summary = XElement.Parse(documentation!).Element("summary");
        }
        catch (XmlException)
        {
            // Invalid user documentation must not prevent job generation.
        }

        summary ??= new XElement("summary", "Queues ",
            new XElement("see", new XAttribute("cref", method.GetDocumentationCommentId()!)), ".");
        var remarks = new XElement("remarks", new XElement("para", "Job name: ", new XElement("c", name), "."),
            new XElement("para", "Handler: ",
                new XElement("see", new XAttribute("cref", method.GetDocumentationCommentId()!)), "."),
            new XElement("para", "Payload: ", new XElement("c", method.Parameters[0].Type.ToDisplayString()), "."),
            new XElement("para",
                "Pass this definition to IJobClient.Enqueue, Schedule, Recurring, or Cron. Use With(payload) to prepare a Chain step."));
        foreach (string line in (summary.ToString() + "\n" + remarks).Replace("\r\n", "\n").Split('\n'))
            source.Append("/// ").Append(line).Append('\n');
    }

    private static bool IsValid(IMethodSymbol m) => !m.IsStatic && !m.IsGenericMethod && !m.IsAbstract &&
                                                    m.MethodKind == MethodKind.Ordinary &&
                                                    m.DeclaredAccessibility == Accessibility.Public &&
                                                    m.ContainingType.TypeKind == TypeKind.Class &&
                                                    !m.ContainingType.IsAbstract && !m.ContainingType.IsGenericType &&
                                                    m.ContainingType.ContainingType is null &&
                                                    m.ContainingType.DeclaredAccessibility == Accessibility.Public &&
                                                    m.Parameters.Length == 2 &&
                                                    m.Parameters.All(x => x.RefKind == RefKind.None) &&
                                                    m.Parameters[0].Type.TypeKind is not (TypeKind.Pointer
                                                        or TypeKind.FunctionPointer or TypeKind.TypeParameter) &&
                                                    !m.Parameters[0].Type.IsRefLikeType &&
                                                    m.Parameters[0].Type.SpecialType != SpecialType.System_Object &&
                                                    m.Parameters[1].Type.ToDisplayString() ==
                                                    "System.Threading.CancellationToken" &&
                                                    m.ReturnType.ToDisplayString() is "System.Threading.Tasks.Task"
                                                        or "System.Threading.Tasks.ValueTask";
}
